### PR TITLE
 Correct link offsets and broken background images

### LINKED ISSUE #44: Scribbles bar is too tall
Scribbles bar is bigger than other bars. I would like it all the same please
screen shot 2018-06-22 at 22 00 20

### PR DESCRIPTION
**Pull request by jnic**
Fixes #44 #45 #49

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
Links are perfect, spacing is perfect, THANK YOU

Issues:
* Tinted overlays for section background images have got lost
* Bar below hero video design has got squashed

**Comment by DeckOfPandas** [comment]
I will start with tagline if you don't mind me adding commits to this PR?

**Comment by jnic** [comment]
Apologies, looks like I lost the "light", "heavy", etc. classes from the divs when I deleted the extras. Please go ahead and re-add those to the containers – should "just work" I think 🙂

**Comment by DeckOfPandas** [comment]
Awesome, will do

**Comment by DeckOfPandas** [comment]
Unfortunately that thing we all know is always true always, but secretly somehow persist in believing might not be true 'this time'..........was true. There is no It Should Just Work. Totally not on you though @jnic !
screen shot 2018-06-27 at 16 04 46

**Comment by DeckOfPandas** [comment]
screen shot 2018-06-27 at 16 08 17

**Comment by DeckOfPandas** [comment]
Onit now

**Comment by jnic** [comment]
That effect is easy enough to get, just blend the images with colors:

Change this:

`background: url('/assets/images/backgrounds/interviews_letterbox.jpg');background-repeat: no-repeat;background-size:cover;`

To this:

`background-color: #ffffff66; background-blend-mode: color; background-image: url('/assets/images/backgrounds/interviews_letterbox.jpg');background-repeat: no-repeat;background-size:cover;`

**Comment by jnic** [comment]
You can turn that into a CSS class like:

```
.light {
   background-color: #ffffff66;
   background-blend-mode: color;
}
```

```
.heavy {
   background-color: #00000066;
   background-blend-mode: color;
}
```

etc.

Make sure you change `background:` to `background-image:` in the HTML 🙂

**Comment by DeckOfPandas** [comment]
I haven't made into CSS like I Should, but.....maybe next time (lol)

**Comment by DeckOfPandas** [comment]
You are the best ever. Thank you.

**Pull request merged**
